# Generated by Django 3.1.2 on 2020-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plasmaregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('mob_number', models.IntegerField()),
                ('email_id', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=30)),
                ('recovered_date', models.DateField()),
            ],
        ),
    ]
